apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-ojue
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-ojue
    app.kubernetes.io/part-of: test-app-agcc
  name: test-component-ojue
  namespace: build-e2e-ccfq-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-ojue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-ojue
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images:e98abf5133944753a5710c5fef558725
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
